# IEEE

In [16]:
# Comment out the following line to run the notebook in CPU mode
import plotly.express as px
import pandas as pd

# Suppress warnings
import warnings
from IPython.display import display
import json
import os
from tqdm import tqdm
from pathlib import Path

warnings.filterwarnings("ignore")

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", message=".*column_view.*")

root_dir = os.path.dirname(os.getcwd())  # Use current working directory as root_dir
display("Running in root dir: ", os.path.basename(root_dir))

output_dir = Path() / "ancova_ieee"
output_dir.mkdir(parents=True, exist_ok=True)
print("Output directory:", output_dir.absolute())

'Running in root dir: '

'freesurfer-fuzzy'

Output directory: /mnt/lustre/ychatel/living-park/VIP-python-client/example/freesurfer-fuzzy/notebooks/ancova_ieee

In [17]:
def get_cohort_stat():
    df_cohort = pd.read_csv("../cohort_stat.csv")
    print(f"Load cohort stats: {os.path.abspath('../cohort_stat.csv')}")
    columns = [
        "PATNO",
        "first_visit",
        "second_visit",
        "dx_group",
        "SEX",
        "AGE_AT_VISIT",
    ]
    df_cohort["first_visit"] = (
        "sub-"
        + df_cohort["PATNO"].astype(str)
        + "_ses-"
        + df_cohort["EVENT_ID"].astype(str)
    )
    df_cohort["second_visit"] = (
        "sub-"
        + df_cohort["PATNO"].astype(str)
        + "_ses-"
        + df_cohort["NEXT_VISIT"].astype(str)
    )
    # Remove PD-MCI subjects
    df_cohort = df_cohort[df_cohort["dx_group"] != "PD-MCI"]
    print(f"Number of PD-non-MCI subjects: {df_cohort.shape[0]}")
    return df_cohort[columns]


df_cohort = get_cohort_stat()

Load cohort stats: /mnt/lustre/ychatel/living-park/VIP-python-client/example/freesurfer-fuzzy/cohort_stat.csv
Number of PD-non-MCI subjects: 270

# ANCOVA

## Cortical

In [18]:
def read_table(hemi, measure):
    df = pd.read_csv(f"table_ieee/{hemi}.aparc.{measure}.tsv", sep="\t")
    df["hemi"] = hemi
    df.columns = [c.replace(f"{hemi}.", "") for c in df.columns]
    df.columns = [c.replace(f"{hemi}_", "") for c in df.columns]
    df.columns = [c.replace(f"_{measure}", "") for c in df.columns]
    df.rename(columns={f"aparc.{measure}": "first_visit"}, inplace=True)
    return df


def read_measure(measure):
    lh = read_table("lh", measure)
    rh = read_table("rh", measure)
    return pd.concat([lh, rh], axis=0)


def get_baseline_ancova(metric):
    df = read_measure(metric)
    df = df.melt(id_vars=["first_visit", "hemi"], var_name="region", value_name=metric)
    df = pd.merge(df, df_cohort, on="first_visit")
    df = df[["first_visit", "hemi", "region", metric, "dx_group", "AGE_AT_VISIT"]]
    return df

In [19]:
import pingouin as pg


def compute_ancova(measure, clinical_df, force):
    if not force and os.path.exists(f"ancova_ieee/pcorr_{measure}.csv"):
        return pd.read_csv(f"ancova_ieee/pcorr_{measure}.csv")

    df = get_baseline_ancova(measure)
    df = pd.merge(
        df,
        clinical_df,
        left_on="first_visit",
        right_on="first_visit",
        suffixes=("", "_clinical"),
    )
    df = df[
        ["first_visit", "region", measure, "hemi", "dx_group", "AGE_AT_VISIT", "SEX"]
    ]

    ancova_df = pd.DataFrame(columns=["hemisphere", "region", "F", "pval"])
    for hemi in df["hemi"].unique():
        for region in df["region"].unique():
            df_region = df[(df["hemi"] == hemi) & (df["region"] == region)]
            ancova = pg.ancova(
                data=df_region,
                dv=measure,
                between="dx_group",
                covar=["AGE_AT_VISIT", "SEX"],
            )
            (F, pval) = ancova["F"].values[0], ancova["p-unc"].values[0]
            ancova_df.loc[len(ancova_df)] = [hemi, region, F, pval]

    filename = output_dir / f"ancova_baseline_{measure}.csv"
    ancova_df.to_csv(filename, index=False)

    return ancova_df

In [20]:
ancova_volume = compute_ancova("volume", df_cohort, force=True)
ancova_thickness = compute_ancova("thickness", df_cohort, force=True)
ancova_area = compute_ancova("area", df_cohort, force=True)

In [21]:
ancova_volume[ancova_volume["pval"] < 0.05].sort_values("F", ascending=False)

   hemisphere                    region          F      pval
61         rh      rostralmiddlefrontal  24.475150  0.000001
37         rh   caudalanteriorcingulate  21.467455  0.000006
34         lh        BrainSegVolNotVent  19.195154  0.000017
70         rh        BrainSegVolNotVent  19.195154  0.000017
46         rh      lateralorbitofrontal  17.332902  0.000042
60         rh  rostralanteriorcingulate  15.527914  0.000104
21         lh        posteriorcingulate  14.594114  0.000166
53         rh             parsorbitalis  13.012982  0.000369
16         lh           parsopercularis  11.652634  0.000741
35         lh                      eTIV  11.569986  0.000773
71         rh                      eTIV  11.569986  0.000773
10         lh      lateralorbitofrontal  11.470754  0.000814
18         lh          parstriangularis  11.438954  0.000827
64         rh          superiortemporal  11.198230  0.000937
54         rh          parstriangularis   8.989577  0.002972
69         rh                    insula   8.981119  0.002986
33         lh                    insula   8.777157  0.003326
52         rh           parsopercularis   8.713302  0.003441
57         rh        posteriorcingulate   8.629961  0.003597
28         lh          superiortemporal   8.503030  0.003848
25         lh      rostralmiddlefrontal   7.874494  0.005384
36         rh                  bankssts   6.905199  0.009094
48         rh       medialorbitofrontal   6.200507  0.013382
6          lh          inferiorparietal   6.152441  0.013742
23         lh                 precuneus   5.610668  0.018566
15         lh               paracentral   5.338522  0.021625
24         lh  rostralanteriorcingulate   5.105816  0.024655
49         rh            middletemporal   5.015945  0.025941
13         lh            middletemporal   4.762452  0.029962
59         rh                 precuneus   4.533196  0.034162
17         lh             parsorbitalis   4.454464  0.035744
29         lh             supramarginal   4.363811  0.037661
41         rh                  fusiform   4.165719  0.042237
5          lh                  fusiform   4.084978  0.044268
20         lh               postcentral   4.084631  0.044277
2          lh       caudalmiddlefrontal   4.084099  0.044290
22         lh                precentral   4.024081  0.045867
62         rh           superiorfrontal   3.985501  0.046913

In [22]:
ancova_thickness[ancova_thickness["pval"] < 0.05].sort_values("F", ascending=False)

   hemisphere              region          F      pval
35         lh  BrainSegVolNotVent  19.195154  0.000017
72         rh  BrainSegVolNotVent  19.195154  0.000017
36         lh                eTIV  11.569986  0.000773
73         rh                eTIV  11.569986  0.000773
51         rh     parahippocampal  10.466433  0.001369

In [23]:
ancova_area[ancova_area["pval"] < 0.05].sort_values("F", ascending=False)

   hemisphere                    region          F      pval
38         rh   caudalanteriorcingulate  24.125025  0.000002
62         rh      rostralmiddlefrontal  23.820015  0.000002
72         rh        BrainSegVolNotVent  19.195154  0.000017
35         lh        BrainSegVolNotVent  19.195154  0.000017
18         lh          parstriangularis  15.032011  0.000133
71         rh             WhiteSurfArea  14.101153  0.000213
21         lh        posteriorcingulate  13.966403  0.000228
54         rh             parsorbitalis  13.946635  0.000230
16         lh           parsopercularis  13.707017  0.000260
34         lh             WhiteSurfArea  13.278499  0.000323
50         rh            middletemporal  12.782789  0.000415
47         rh      lateralorbitofrontal  12.498100  0.000480
61         rh  rostralanteriorcingulate  12.305231  0.000530
65         rh          superiortemporal  12.042355  0.000607
55         rh          parstriangularis  11.764787  0.000700
36         lh                      eTIV  11.569986  0.000773
73         rh                      eTIV  11.569986  0.000773
37         rh                  bankssts  11.250046  0.000912
53         rh           parsopercularis  10.316114  0.001481
25         lh      rostralmiddlefrontal   9.450110  0.002331
10         lh      lateralorbitofrontal   9.441072  0.002342
58         rh        posteriorcingulate   8.723166  0.003423
6          lh          inferiorparietal   8.622898  0.003610
13         lh            middletemporal   8.495861  0.003863
70         rh                    insula   8.384075  0.004100
28         lh          superiortemporal   7.902163  0.005305
69         rh        transversetemporal   7.872455  0.005390
17         lh             parsorbitalis   7.687575  0.005953
49         rh       medialorbitofrontal   7.385085  0.007009
23         lh                 precuneus   7.139495  0.008006
33         lh                    insula   7.132333  0.008037
2          lh       caudalmiddlefrontal   7.126027  0.008065
67         rh               frontalpole   7.053667  0.008388
63         rh           superiorfrontal   6.984877  0.008708
44         rh          inferiortemporal   6.502049  0.011336
7          lh          inferiortemporal   6.368686  0.012198
60         rh                 precuneus   6.317705  0.012545
43         rh          inferiorparietal   6.270434  0.012876
26         lh           superiorfrontal   5.912340  0.015696
24         lh  rostralanteriorcingulate   5.900804  0.015797
32         lh        transversetemporal   5.598921  0.018689
42         rh                  fusiform   5.406368  0.020816
20         lh               postcentral   5.208569  0.023266
5          lh                  fusiform   5.153843  0.023995
29         lh             supramarginal   5.043754  0.025536
68         rh              temporalpole   4.311257  0.038821
1          lh   caudalanteriorcingulate   4.149310  0.042642
66         rh             supramarginal   4.146371  0.042714
19         lh             pericalcarine   4.097609  0.043943

## Subcortical Volume

In [24]:
df = pd.read_csv("table_ieee/aseg.volume.tsv", sep="\t")
df.rename(columns={"Measure:volume": "first_visit"}, inplace=True)
df = df.melt(id_vars=["first_visit"], var_name="region", value_name="volume")
df = pd.merge(
    df,
    df_cohort,
    left_on="first_visit",
    right_on="first_visit",
    suffixes=("", "_clinical"),
)
df = df[["first_visit", "region", "volume", "dx_group", "AGE_AT_VISIT", "SEX"]]

ancova_subcortical_volume_df = pd.DataFrame(columns=["region", "F", "pval"])
for region in tqdm(df["region"].unique()):
    df_region = df[df["region"] == region]
    ancova = pg.ancova(
        data=df_region, dv="volume", between="dx_group", covar=["AGE_AT_VISIT", "SEX"]
    )
    (F, pval) = ancova["F"].values[0], ancova["p-unc"].values[0]
    ancova_subcortical_volume_df.loc[len(ancova_subcortical_volume_df)] = [
        region,
        F,
        pval,
    ]

filename = output_dir / "ancova_baseline_subcortical_volume.csv"
ancova_subcortical_volume_df.to_csv(filename, index=False)

ancova_subcortical_volume_df[ancova_subcortical_volume_df["pval"] < 0.05].sort_values(
    "F", ascending=False
)

 55%|████████████████████████████████████████████████████████████████████████████████▉                                                                   | 35/64 [00:00<00:00, 80.23it/s]

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:00<00:00, 80.12it/s]

                           region          F      pval
46             BrainSegVolNotVent  19.195154  0.000017
25                 Right-Pallidum  18.308144  0.000026
3          Left-Cerebellum-Cortex  17.802033  0.000034
45                    BrainSegVol  16.807146  0.000055
56       SupraTentorialVolNotVent  16.644754  0.000060
10                     Brain-Stem  16.230835  0.000073
22                 Right-Thalamus  15.426325  0.000109
29                Right-VentralDC  15.037277  0.000133
57                        MaskVol  15.025067  0.000134
4                   Left-Thalamus  14.873146  0.000144
54                   TotalGrayVol  14.786547  0.000151
55              SupraTentorialVol  14.414760  0.000182
51       rhCerebralWhiteMatterVol  14.368339  0.000186
21        Right-Cerebellum-Cortex  13.430245  0.000299
15                 Left-VentralDC  12.118389  0.000583
52         CerebralWhiteMatterVol  12.064974  0.000600
63  EstimatedTotalIntraCranialVol  11.569986  0.000773
53                 SubCortGrayVol  11.412072  0.000839
43                CC_Mid_Anterior  11.082530  0.000995
20  Right-Cerebellum-White-Matter  11.011921  0.001032
26              Right-Hippocampus  10.871737  0.001109
48                    rhCortexVol  10.478268  0.001361
49                      CortexVol  10.329397  0.001471
47                    lhCortexVol  10.061388  0.001692
2    Left-Cerebellum-White-Matter   9.601446  0.002153
7                   Left-Pallidum   9.233516  0.002613
50       lhCerebralWhiteMatterVol   9.109041  0.002790
42                     CC_Central   5.799398  0.016712
28           Right-Accumbens-area   5.498550  0.019768
11               Left-Hippocampus   4.022780  0.045902